kind: pipeline
type: vm
name: linux-amd64
platform:
  os: linux
  arch: amd64
pool:
  use: ubuntu

steps:
  - name: environment
    image: golang:1.18
    pull: always
    environment:
      CGO_ENABLED: "0"
    commands:
      - go version
      - go env
  - name: build
    image: golang:1.18
    environment:
      CGO_ENABLED: "0"
    commands:
      - go build -v -ldflags "-X main.version=" -a -tags netgo -o release/linux/amd64/drone-manifest .
  - name: docker
    image: plugins/docker
    settings:
      dockerfile: docker/Dockerfile.linux.amd64
      repo: plugins/stackrox
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      auto_tag: true
      auto_tag_suffix: linux-amd64
trigger:
  ref:
    - refs/heads/main
    - refs/tags/**
    - refs/pull/**
